//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public long IDWebsite { get; set; }
        public string PositionName { get; set; }
        public string CompanyName { get; set; }
        public string ManagerName { get; set; }
        public string PhoneLine1 { get; set; }
        public string PhoneLine2 { get; set; }
        public string PhoneLine3 { get; set; }
        public string CompanyAddress { get; set; }
        public string ThumnailMapPath { get; set; }
        public string GoogleMapScript { get; set; }
        public string ExtraMessage { get; set; }
    }
}
