//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Provinces = new HashSet<Provinces>();
        }
    
        public long IDCountry { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<Provinces> Provinces { get; set; }
    }
}
