//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaTypes
    {
        public MediaTypes()
        {
            this.MediaGallery = new HashSet<MediaGallery>();
        }
    
        public int IDMediaType { get; set; }
        public string MediaTypeTitle { get; set; }
        public string ResourcesPrefix { get; set; }
    
        public virtual ICollection<MediaGallery> MediaGallery { get; set; }
    }
}
