//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaGallery
    {
        public int IDGalleryItem { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public string ItemTitle { get; set; }
        public string ThumbnailImagePath { get; set; }
        public string ResourcePath { get; set; }
        public string ItemDescription { get; set; }
        public int MediaTypeID { get; set; }
        public bool Published { get; set; }
        public int SortOrder { get; set; }
        public string MediaTags { get; set; }
    
        public virtual MediaAlbums MediaAlbums { get; set; }
        public virtual MediaTypes MediaTypes { get; set; }
    }
}
