//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provinces
    {
        public Provinces()
        {
            this.Cities = new HashSet<Cities>();
        }
    
        public long CountryID { get; set; }
        public long IDProvince { get; set; }
        public string ProvinceName { get; set; }
    
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual Countries Countries { get; set; }
    }
}
