//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitePages
    {
        public SitePages()
        {
            this.SitePageFragments = new HashSet<SitePageFragments>();
        }
    
        public int IDPage { get; set; }
        public string PageInternalName { get; set; }
        public string PageTitle { get; set; }
        public string PageContent { get; set; }
        public Nullable<bool> HasFragments { get; set; }
        public bool Published { get; set; }
        public bool IsMetaEditable { get; set; }
        public bool IsScript { get; set; }
    
        public virtual ICollection<SitePageFragments> SitePageFragments { get; set; }
    }
}
