//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderImages
    {
        public int SliderID { get; set; }
        public int SlideIndex { get; set; }
        public string ThumbnailImagePath { get; set; }
        public string ImagePath { get; set; }
        public string SlideTitle { get; set; }
        public string SlideDescription { get; set; }
        public bool Published { get; set; }
    
        public virtual Sliders Sliders { get; set; }
    }
}
