//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sliders
    {
        public Sliders()
        {
            this.SliderImages = new HashSet<SliderImages>();
        }
    
        public int IDSlider { get; set; }
        public string InternalName { get; set; }
        public string SliderWith { get; set; }
        public string SliderHeight { get; set; }
        public bool Published { get; set; }
    
        public virtual ICollection<SliderImages> SliderImages { get; set; }
    }
}
