//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialDataEntities : DbContext
    {
        public SocialDataEntities()
            : base("name=SocialDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cities> Cities { get; set; }
        public DbSet<CompanyInfo> CompanyInfo { get; set; }
        public DbSet<ContactUs> ContactUs { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<MediaAlbums> MediaAlbums { get; set; }
        public DbSet<MediaGallery> MediaGallery { get; set; }
        public DbSet<MediaTypes> MediaTypes { get; set; }
        public DbSet<PostContentFragments> PostContentFragments { get; set; }
        public DbSet<Posts> Posts { get; set; }
        public DbSet<Provinces> Provinces { get; set; }
        public DbSet<SitePageFragments> SitePageFragments { get; set; }
        public DbSet<SitePages> SitePages { get; set; }
        public DbSet<SliderImages> SliderImages { get; set; }
        public DbSet<Sliders> Sliders { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
