//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSS_Victim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Posts = new HashSet<Posts>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int IDUser { get; set; }
        public string UserFullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EMail { get; set; }
        public string RegisterationDateTime { get; set; }
        public System.DateTime RegisterationDateTimeGregorian { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Description { get; set; }
        public string WebAddress { get; set; }
        public string AddressCountryName { get; set; }
        public string AddressProvinceName { get; set; }
        public string AddressCityName { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public bool IsApproved { get; set; }
        public bool IsEmployee { get; set; }
        public string ProfilePicturePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posts> Posts { get; set; }
        public virtual webpages_Membership webpages_Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
