using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

namespace RoyaMVC_EN
{
    public static class MIMEAssister
    {
        public static readonly List<KeyValuePair<string, string>> MIMETypesDictionary =
            new List<KeyValuePair<string, string>> {
                new KeyValuePair<string, string>("3dm",	"x-world/x-3dmf"),
                new KeyValuePair<string, string>("3dmf",	"x-world/x-3dmf"),
                new KeyValuePair<string, string>("a",	"application/octet-stream"),
                new KeyValuePair<string, string>("aab",	"application/x-authorware-bin"),
                new KeyValuePair<string, string>("aam",	"application/x-authorware-map"),
                new KeyValuePair<string, string>("aas",	"application/x-authorware-seg"),
                new KeyValuePair<string, string>("abc",	"text/vnd.abc"),
                new KeyValuePair<string, string>("acgi",	"text/html"),
                new KeyValuePair<string, string>("afl",	"video/animaflex"),
                new KeyValuePair<string, string>("ai",	"application/postscript"),
                new KeyValuePair<string, string>("aif",	"audio/aiff"),
                new KeyValuePair<string, string>("aif",	"audio/x-aiff"),
                new KeyValuePair<string, string>("aifc",	"audio/aiff"),
                new KeyValuePair<string, string>("aifc",	"audio/x-aiff"),
                new KeyValuePair<string, string>("aiff",	"audio/aiff"),
                new KeyValuePair<string, string>("aiff",	"audio/x-aiff"),
                new KeyValuePair<string, string>("aim",	"application/x-aim"),
                new KeyValuePair<string, string>("aip",	"text/x-audiosoft-intra"),
                new KeyValuePair<string, string>("ani",	"application/x-navi-animation"),
                new KeyValuePair<string, string>("aos",	"application/x-nokia-9000-communicator-add-on-software"),
                new KeyValuePair<string, string>("aps",	"application/mime"),
                new KeyValuePair<string, string>("arc",	"application/octet-stream"),
                new KeyValuePair<string, string>("arj",	"application/arj"),
                new KeyValuePair<string, string>("arj",	"application/octet-stream"),
                new KeyValuePair<string, string>("art",	"image/x-jg"),
                new KeyValuePair<string, string>("asf",	"video/x-ms-asf"),
                new KeyValuePair<string, string>("asm",	"text/x-asm"),
                new KeyValuePair<string, string>("asp",	"text/asp"),
                new KeyValuePair<string, string>("asx",	"application/x-mplayer2"),
                new KeyValuePair<string, string>("asx",	"video/x-ms-asf"),
                new KeyValuePair<string, string>("asx",	"video/x-ms-asf-plugin"),
                new KeyValuePair<string, string>("au",	"audio/basic"),
                new KeyValuePair<string, string>("au",	"audio/x-au"),
                new KeyValuePair<string, string>("avi",	"application/x-troff-msvideo"),
                new KeyValuePair<string, string>("avi",	"video/avi"),
                new KeyValuePair<string, string>("avi",	"video/msvideo"),
                new KeyValuePair<string, string>("avi",	"video/x-msvideo"),
                new KeyValuePair<string, string>("avs",	"video/avs-video"),
                new KeyValuePair<string, string>("bcpio",	"application/x-bcpio"),
                new KeyValuePair<string, string>("bin",	"application/mac-binary"),
                new KeyValuePair<string, string>("bin",	"application/macbinary"),
                new KeyValuePair<string, string>("bin",	"application/octet-stream"),
                new KeyValuePair<string, string>("bin",	"application/x-binary"),
                new KeyValuePair<string, string>("bin",	"application/x-macbinary"),
                new KeyValuePair<string, string>("bm",	"image/bmp"),
                new KeyValuePair<string, string>("bmp",	"image/bmp"),
                new KeyValuePair<string, string>("bmp",	"image/x-windows-bmp"),
                new KeyValuePair<string, string>("boo",	"application/book"),
                new KeyValuePair<string, string>("book",	"application/book"),
                new KeyValuePair<string, string>("boz",	"application/x-bzip2"),
                new KeyValuePair<string, string>("bsh",	"application/x-bsh"),
                new KeyValuePair<string, string>("bz",	"application/x-bzip"),
                new KeyValuePair<string, string>("bz2",	"application/x-bzip2"),
                new KeyValuePair<string, string>("c",	"text/plain"),
                new KeyValuePair<string, string>("c",	"text/x-c"),
                new KeyValuePair<string, string>("c++",	"text/plain"),
                new KeyValuePair<string, string>("cat",	"application/vnd.ms-pki.seccat"),
                new KeyValuePair<string, string>("cc",	"text/plain"),
                new KeyValuePair<string, string>("cc",	"text/x-c"),
                new KeyValuePair<string, string>("ccad",	"application/clariscad"),
                new KeyValuePair<string, string>("cco",	"application/x-cocoa"),
                new KeyValuePair<string, string>("cdf",	"application/cdf"),
                new KeyValuePair<string, string>("cdf",	"application/x-cdf"),
                new KeyValuePair<string, string>("cdf",	"application/x-netcdf"),
                new KeyValuePair<string, string>("cer",	"application/pkix-cert"),
                new KeyValuePair<string, string>("cer",	"application/x-x509-ca-cert"),
                new KeyValuePair<string, string>("cha",	"application/x-chat"),
                new KeyValuePair<string, string>("chat",	"application/x-chat"),
                new KeyValuePair<string, string>("class",	"application/java"),
                new KeyValuePair<string, string>("class",	"application/java-byte-code"),
                new KeyValuePair<string, string>("class",	"application/x-java-class"),
                new KeyValuePair<string, string>("com",	"application/octet-stream"),
                new KeyValuePair<string, string>("com",	"text/plain"),
                new KeyValuePair<string, string>("conf",	"text/plain"),
                new KeyValuePair<string, string>("cpio",	"application/x-cpio"),
                new KeyValuePair<string, string>("cpp",	"text/x-c"),
                new KeyValuePair<string, string>("cpt",	"application/mac-compactpro"),
                new KeyValuePair<string, string>("cpt",	"application/x-compactpro"),
                new KeyValuePair<string, string>("cpt",	"application/x-cpt"),
                new KeyValuePair<string, string>("crl",	"application/pkcs-crl"),
                new KeyValuePair<string, string>("crl",	"application/pkix-crl"),
                new KeyValuePair<string, string>("crt",	"application/pkix-cert"),
                new KeyValuePair<string, string>("crt",	"application/x-x509-ca-cert"),
                new KeyValuePair<string, string>("crt",	"application/x-x509-user-cert"),
                new KeyValuePair<string, string>("csh",	"application/x-csh"),
                new KeyValuePair<string, string>("csh",	"text/x-script.csh"),
                new KeyValuePair<string, string>("css",	"application/x-pointplus"),
                new KeyValuePair<string, string>("css",	"text/css"),
                new KeyValuePair<string, string>("cxx",	"text/plain"),
                new KeyValuePair<string, string>("dcr",	"application/x-director"),
                new KeyValuePair<string, string>("deepv",	"application/x-deepv"),
                new KeyValuePair<string, string>("def",	"text/plain"),
                new KeyValuePair<string, string>("der",	"application/x-x509-ca-cert"),
                new KeyValuePair<string, string>("dif",	"video/x-dv"),
                new KeyValuePair<string, string>("dir",	"application/x-director"),
                new KeyValuePair<string, string>("dl",	"video/dl"),
                new KeyValuePair<string, string>("dl",	"video/x-dl"),
                new KeyValuePair<string, string>("doc",	"application/msword"),
                new KeyValuePair<string, string>("dot",	"application/msword"),
                new KeyValuePair<string, string>("dp",	"application/commonground"),
                new KeyValuePair<string, string>("drw",	"application/drafting"),
                new KeyValuePair<string, string>("dump",	"application/octet-stream"),
                new KeyValuePair<string, string>("dv",	"video/x-dv"),
                new KeyValuePair<string, string>("dvi",	"application/x-dvi"),
                new KeyValuePair<string, string>("dwf",	"drawing/x-dwf (old)"),
                new KeyValuePair<string, string>("dwf",	"model/vnd.dwf"),
                new KeyValuePair<string, string>("dwg",	"application/acad"),
                new KeyValuePair<string, string>("dwg",	"image/vnd.dwg"),
                new KeyValuePair<string, string>("dwg",	"image/x-dwg"),
                new KeyValuePair<string, string>("dxf",	"application/dxf"),
                new KeyValuePair<string, string>("dxf",	"image/vnd.dwg"),
                new KeyValuePair<string, string>("dxf",	"image/x-dwg"),
                new KeyValuePair<string, string>("dxr",	"application/x-director"),
                new KeyValuePair<string, string>("el",	"text/x-script.elisp"),
                new KeyValuePair<string, string>("elc",	"application/x-bytecode.elisp (compiled elisp)"),
                new KeyValuePair<string, string>("elc",	"application/x-elc"),
                new KeyValuePair<string, string>("env",	"application/x-envoy"),
                new KeyValuePair<string, string>("eps",	"application/postscript"),
                new KeyValuePair<string, string>("es",	"application/x-esrehber"),
                new KeyValuePair<string, string>("etx",	"text/x-setext"),
                new KeyValuePair<string, string>("evy",	"application/envoy"),
                new KeyValuePair<string, string>("evy",	"application/x-envoy"),
                new KeyValuePair<string, string>("exe",	"application/octet-stream"),
                new KeyValuePair<string, string>("f",	"text/plain"),
                new KeyValuePair<string, string>("f",	"text/x-fortran"),
                new KeyValuePair<string, string>("f77",	"text/x-fortran"),
                new KeyValuePair<string, string>("f90",	"text/plain"),
                new KeyValuePair<string, string>("f90",	"text/x-fortran"),
                new KeyValuePair<string, string>("fdf",	"application/vnd.fdf"),
                new KeyValuePair<string, string>("fif",	"application/fractals"),
                new KeyValuePair<string, string>("fif",	"image/fif"),
                new KeyValuePair<string, string>("fli",	"video/fli"),
                new KeyValuePair<string, string>("fli",	"video/x-fli"),
                new KeyValuePair<string, string>("flo",	"image/florian"),
                new KeyValuePair<string, string>("flx",	"text/vnd.fmi.flexstor"),
                new KeyValuePair<string, string>("fmf",	"video/x-atomic3d-feature"),
                new KeyValuePair<string, string>("for",	"text/plain"),
                new KeyValuePair<string, string>("for",	"text/x-fortran"),
                new KeyValuePair<string, string>("fpx",	"image/vnd.fpx"),
                new KeyValuePair<string, string>("fpx",	"image/vnd.net-fpx"),
                new KeyValuePair<string, string>("frl",	"application/freeloader"),
                new KeyValuePair<string, string>("funk",	"audio/make"),
                new KeyValuePair<string, string>("g",	"text/plain"),
                new KeyValuePair<string, string>("g3",	"image/g3fax"),
                new KeyValuePair<string, string>("gif",	"image/gif"),
                new KeyValuePair<string, string>("gl",	"video/gl"),
                new KeyValuePair<string, string>("gl",	"video/x-gl"),
                new KeyValuePair<string, string>("gsd",	"audio/x-gsm"),
                new KeyValuePair<string, string>("gsm",	"audio/x-gsm"),
                new KeyValuePair<string, string>("gsp",	"application/x-gsp"),
                new KeyValuePair<string, string>("gss",	"application/x-gss"),
                new KeyValuePair<string, string>("gtar",	"application/x-gtar"),
                new KeyValuePair<string, string>("gz",	"application/x-compressed"),
                new KeyValuePair<string, string>("gz",	"application/x-gzip"),
                new KeyValuePair<string, string>("gzip",	"application/x-gzip"),
                new KeyValuePair<string, string>("gzip",	"multipart/x-gzip"),
                new KeyValuePair<string, string>("h",	"text/plain"),
                new KeyValuePair<string, string>("h",	"text/x-h"),
                new KeyValuePair<string, string>("hdf",	"application/x-hdf"),
                new KeyValuePair<string, string>("help",	"application/x-helpfile"),
                new KeyValuePair<string, string>("hgl",	"application/vnd.hp-hpgl"),
                new KeyValuePair<string, string>("hh",	"text/plain"),
                new KeyValuePair<string, string>("hh",	"text/x-h"),
                new KeyValuePair<string, string>("hlb",	"text/x-script"),
                new KeyValuePair<string, string>("hlp",	"application/hlp"),
                new KeyValuePair<string, string>("hlp",	"application/x-helpfile"),
                new KeyValuePair<string, string>("hlp",	"application/x-winhelp"),
                new KeyValuePair<string, string>("hpg",	"application/vnd.hp-hpgl"),
                new KeyValuePair<string, string>("hpgl",	"application/vnd.hp-hpgl"),
                new KeyValuePair<string, string>("hqx",	"application/binhex"),
                new KeyValuePair<string, string>("hqx",	"application/binhex4"),
                new KeyValuePair<string, string>("hqx",	"application/mac-binhex"),
                new KeyValuePair<string, string>("hqx",	"application/mac-binhex40"),
                new KeyValuePair<string, string>("hqx",	"application/x-binhex40"),
                new KeyValuePair<string, string>("hqx",	"application/x-mac-binhex40"),
                new KeyValuePair<string, string>("hta",	"application/hta"),
                new KeyValuePair<string, string>("htc",	"text/x-component"),
                new KeyValuePair<string, string>("htm",	"text/html"),
                new KeyValuePair<string, string>("html",	"text/html"),
                new KeyValuePair<string, string>("htmls",	"text/html"),
                new KeyValuePair<string, string>("htt",	"text/webviewhtml"),
                new KeyValuePair<string, string>("htx",	"text/html"),
                new KeyValuePair<string, string>("ice",	"x-conference/x-cooltalk"),
                new KeyValuePair<string, string>("ico",	"image/x-icon"),
                new KeyValuePair<string, string>("idc",	"text/plain"),
                new KeyValuePair<string, string>("ief",	"image/ief"),
                new KeyValuePair<string, string>("iefs",	"image/ief"),
                new KeyValuePair<string, string>("iges",	"application/iges"),
                new KeyValuePair<string, string>("iges",	"model/iges"),
                new KeyValuePair<string, string>("igs",	"application/iges"),
                new KeyValuePair<string, string>("igs",	"model/iges"),
                new KeyValuePair<string, string>("ima",	"application/x-ima"),
                new KeyValuePair<string, string>("imap",	"application/x-httpd-imap"),
                new KeyValuePair<string, string>("inf",	"application/inf"),
                new KeyValuePair<string, string>("ins",	"application/x-internett-signup"),
                new KeyValuePair<string, string>("ip",	"application/x-ip2"),
                new KeyValuePair<string, string>("isu",	"video/x-isvideo"),
                new KeyValuePair<string, string>("it",	"audio/it"),
                new KeyValuePair<string, string>("iv",	"application/x-inventor"),
                new KeyValuePair<string, string>("ivr",	"i-world/i-vrml"),
                new KeyValuePair<string, string>("ivy",	"application/x-livescreen"),
                new KeyValuePair<string, string>("jam",	"audio/x-jam"),
                new KeyValuePair<string, string>("jav",	"text/plain"),
                new KeyValuePair<string, string>("jav",	"text/x-java-source"),
                new KeyValuePair<string, string>("java",	"text/plain"),
                new KeyValuePair<string, string>("java",	"text/x-java-source"),
                new KeyValuePair<string, string>("jcm",	"application/x-java-commerce"),
                new KeyValuePair<string, string>("jfif",	"image/jpeg"),
                new KeyValuePair<string, string>("jfif",	"image/pjpeg"),
                new KeyValuePair<string, string>("jfif-tbnl",	"image/jpeg"),
                new KeyValuePair<string, string>("jpe",	"image/jpeg"),
                new KeyValuePair<string, string>("jpe",	"image/pjpeg"),
                new KeyValuePair<string, string>("jpeg",	"image/jpeg"),
                new KeyValuePair<string, string>("jpeg",	"image/pjpeg"),
                new KeyValuePair<string, string>("jpg",	"image/jpeg"),
                new KeyValuePair<string, string>("jpg",	"image/pjpeg"),
                new KeyValuePair<string, string>("jps",	"image/x-jps"),
                new KeyValuePair<string, string>("js",	"application/x-javascript"),
                new KeyValuePair<string, string>("jut",	"image/jutvision"),
                new KeyValuePair<string, string>("kar",	"audio/midi"),
                new KeyValuePair<string, string>("kar",	"music/x-karaoke"),
                new KeyValuePair<string, string>("ksh",	"application/x-ksh"),
                new KeyValuePair<string, string>("ksh",	"text/x-script.ksh"),
                new KeyValuePair<string, string>("la",	"audio/nspaudio"),
                new KeyValuePair<string, string>("la",	"audio/x-nspaudio"),
                new KeyValuePair<string, string>("lam",	"audio/x-liveaudio"),
                new KeyValuePair<string, string>("latex",	"application/x-latex"),
                new KeyValuePair<string, string>("lha",	"application/lha"),
                new KeyValuePair<string, string>("lha",	"application/octet-stream"),
                new KeyValuePair<string, string>("lha",	"application/x-lha"),
                new KeyValuePair<string, string>("lhx",	"application/octet-stream"),
                new KeyValuePair<string, string>("list",	"text/plain"),
                new KeyValuePair<string, string>("lma",	"audio/nspaudio"),
                new KeyValuePair<string, string>("lma",	"audio/x-nspaudio"),
                new KeyValuePair<string, string>("log",	"text/plain"),
                new KeyValuePair<string, string>("lsp",	"application/x-lisp"),
                new KeyValuePair<string, string>("lsp",	"text/x-script.lisp"),
                new KeyValuePair<string, string>("lst",	"text/plain"),
                new KeyValuePair<string, string>("lsx",	"text/x-la-asf"),
                new KeyValuePair<string, string>("ltx",	"application/x-latex"),
                new KeyValuePair<string, string>("lzh",	"application/octet-stream"),
                new KeyValuePair<string, string>("lzh",	"application/x-lzh"),
                new KeyValuePair<string, string>("lzx",	"application/lzx"),
                new KeyValuePair<string, string>("lzx",	"application/octet-stream"),
                new KeyValuePair<string, string>("lzx",	"application/x-lzx"),
                new KeyValuePair<string, string>("m",	"text/plain"),
                new KeyValuePair<string, string>("m",	"text/x-m"),
                new KeyValuePair<string, string>("m1v",	"video/mpeg"),
                new KeyValuePair<string, string>("m2a",	"audio/mpeg"),
                new KeyValuePair<string, string>("m2v",	"video/mpeg"),
                new KeyValuePair<string, string>("m3u",	"audio/x-mpequrl"),
                new KeyValuePair<string, string>("man",	"application/x-troff-man"),
                new KeyValuePair<string, string>("map",	"application/x-navimap"),
                new KeyValuePair<string, string>("mar",	"text/plain"),
                new KeyValuePair<string, string>("mbd",	"application/mbedlet"),
                new KeyValuePair<string, string>("mc$",	"application/x-magic-cap-package-1.0"),
                new KeyValuePair<string, string>("mcd",	"application/mcad"),
                new KeyValuePair<string, string>("mcd",	"application/x-mathcad"),
                new KeyValuePair<string, string>("mcf",	"image/vasa"),
                new KeyValuePair<string, string>("mcf",	"text/mcf"),
                new KeyValuePair<string, string>("mcp",	"application/netmc"),
                new KeyValuePair<string, string>("me",	"application/x-troff-me"),
                new KeyValuePair<string, string>("mht",	"message/rfc822"),
                new KeyValuePair<string, string>("mhtml",	"message/rfc822"),
                new KeyValuePair<string, string>("mid",	"application/x-midi"),
                new KeyValuePair<string, string>("mid",	"audio/midi"),
                new KeyValuePair<string, string>("mid",	"audio/x-mid"),
                new KeyValuePair<string, string>("mid",	"audio/x-midi"),
                new KeyValuePair<string, string>("mid",	"music/crescendo"),
                new KeyValuePair<string, string>("mid",	"x-music/x-midi"),
                new KeyValuePair<string, string>("midi",	"application/x-midi"),
                new KeyValuePair<string, string>("midi",	"audio/midi"),
                new KeyValuePair<string, string>("midi",	"audio/x-mid"),
                new KeyValuePair<string, string>("midi",	"audio/x-midi"),
                new KeyValuePair<string, string>("midi",	"music/crescendo"),
                new KeyValuePair<string, string>("midi",	"x-music/x-midi"),
                new KeyValuePair<string, string>("mif",	"application/x-frame"),
                new KeyValuePair<string, string>("mif",	"application/x-mif"),
                new KeyValuePair<string, string>("mime",	"message/rfc822"),
                new KeyValuePair<string, string>("mime",	"www/mime"),
                new KeyValuePair<string, string>("mjf",	"audio/x-vnd.audioexplosion.mjuicemediafile"),
                new KeyValuePair<string, string>("mjpg",	"video/x-motion-jpeg"),
                new KeyValuePair<string, string>("mm",	"application/base64"),
                new KeyValuePair<string, string>("mm",	"application/x-meme"),
                new KeyValuePair<string, string>("mme",	"application/base64"),
                new KeyValuePair<string, string>("mod",	"audio/mod"),
                new KeyValuePair<string, string>("mod",	"audio/x-mod"),
                new KeyValuePair<string, string>("moov",	"video/quicktime"),
                new KeyValuePair<string, string>("mov",	"video/quicktime"),
                new KeyValuePair<string, string>("movie",	"video/x-sgi-movie"),
                new KeyValuePair<string, string>("mp2",	"audio/mpeg"),
                new KeyValuePair<string, string>("mp2",	"audio/x-mpeg"),
                new KeyValuePair<string, string>("mp2",	"video/mpeg"),
                new KeyValuePair<string, string>("mp2",	"video/x-mpeg"),
                new KeyValuePair<string, string>("mp2",	"video/x-mpeq2a"),
                new KeyValuePair<string, string>("mp3",	"audio/mpeg3"),
                new KeyValuePair<string, string>("mp3",	"audio/x-mpeg-3"),
                new KeyValuePair<string, string>("mp3",	"video/mpeg"),
                new KeyValuePair<string, string>("mp3",	"video/x-mpeg"),
                new KeyValuePair<string, string>("mpa",	"audio/mpeg"),
                new KeyValuePair<string, string>("mpa",	"video/mpeg"),
                new KeyValuePair<string, string>("mpc",	"application/x-project"),
                new KeyValuePair<string, string>("mpe",	"video/mpeg"),
                new KeyValuePair<string, string>("mpeg",	"video/mpeg"),
                new KeyValuePair<string, string>("mpg",	"audio/mpeg"),
                new KeyValuePair<string, string>("mpg",	"video/mpeg"),
                new KeyValuePair<string, string>("mpga",	"audio/mpeg"),
                new KeyValuePair<string, string>("mpp",	"application/vnd.ms-project"),
                new KeyValuePair<string, string>("mpt",	"application/x-project"),
                new KeyValuePair<string, string>("mpv",	"application/x-project"),
                new KeyValuePair<string, string>("mpx",	"application/x-project"),
                new KeyValuePair<string, string>("mrc",	"application/marc"),
                new KeyValuePair<string, string>("ms",	"application/x-troff-ms"),
                new KeyValuePair<string, string>("mv",	"video/x-sgi-movie"),
                new KeyValuePair<string, string>("my",	"audio/make"),
                new KeyValuePair<string, string>("mzz",	"application/x-vnd.audioexplosion.mzz"),
                new KeyValuePair<string, string>("nap",	"image/naplps"),
                new KeyValuePair<string, string>("naplps",	"image/naplps"),
                new KeyValuePair<string, string>("nc",	"application/x-netcdf"),
                new KeyValuePair<string, string>("ncm",	"application/vnd.nokia.configuration-message"),
                new KeyValuePair<string, string>("nif",	"image/x-niff"),
                new KeyValuePair<string, string>("niff",	"image/x-niff"),
                new KeyValuePair<string, string>("nix",	"application/x-mix-transfer"),
                new KeyValuePair<string, string>("nsc",	"application/x-conference"),
                new KeyValuePair<string, string>("nvd",	"application/x-navidoc"),
                new KeyValuePair<string, string>("o",	"application/octet-stream"),
                new KeyValuePair<string, string>("oda",	"application/oda"),
                new KeyValuePair<string, string>("omc",	"application/x-omc"),
                new KeyValuePair<string, string>("omcd",	"application/x-omcdatamaker"),
                new KeyValuePair<string, string>("omcr",	"application/x-omcregerator"),
                new KeyValuePair<string, string>("p",	"text/x-pascal"),
                new KeyValuePair<string, string>("p10",	"application/pkcs10"),
                new KeyValuePair<string, string>("p10",	"application/x-pkcs10"),
                new KeyValuePair<string, string>("p12",	"application/pkcs-12"),
                new KeyValuePair<string, string>("p12",	"application/x-pkcs12"),
                new KeyValuePair<string, string>("p7a",	"application/x-pkcs7-signature"),
                new KeyValuePair<string, string>("p7c",	"application/pkcs7-mime"),
                new KeyValuePair<string, string>("p7c",	"application/x-pkcs7-mime"),
                new KeyValuePair<string, string>("p7m",	"application/pkcs7-mime"),
                new KeyValuePair<string, string>("p7m",	"application/x-pkcs7-mime"),
                new KeyValuePair<string, string>("p7r",	"application/x-pkcs7-certreqresp"),
                new KeyValuePair<string, string>("p7s",	"application/pkcs7-signature"),
                new KeyValuePair<string, string>("part",	"application/pro_eng"),
                new KeyValuePair<string, string>("pas",	"text/pascal"),
                new KeyValuePair<string, string>("pbm",	"image/x-portable-bitmap"),
                new KeyValuePair<string, string>("pcl",	"application/vnd.hp-pcl"),
                new KeyValuePair<string, string>("pcl",	"application/x-pcl"),
                new KeyValuePair<string, string>("pct",	"image/x-pict"),
                new KeyValuePair<string, string>("pcx",	"image/x-pcx"),
                new KeyValuePair<string, string>("pdb",	"chemical/x-pdb"),
                new KeyValuePair<string, string>("pdf",	"application/pdf"),
                new KeyValuePair<string, string>("pfunk",	"audio/make"),
                new KeyValuePair<string, string>("pfunk",	"audio/make.my.funk"),
                new KeyValuePair<string, string>("pgm",	"image/x-portable-graymap"),
                new KeyValuePair<string, string>("pgm",	"image/x-portable-greymap"),
                new KeyValuePair<string, string>("pic",	"image/pict"),
                new KeyValuePair<string, string>("pict",	"image/pict"),
                new KeyValuePair<string, string>("pkg",	"application/x-newton-compatible-pkg"),
                new KeyValuePair<string, string>("pko",	"application/vnd.ms-pki.pko"),
                new KeyValuePair<string, string>("pl",	"text/plain"),
                new KeyValuePair<string, string>("pl",	"text/x-script.perl"),
                new KeyValuePair<string, string>("plx",	"application/x-pixclscript"),
                new KeyValuePair<string, string>("pm",	"image/x-xpixmap"),
                new KeyValuePair<string, string>("pm",	"text/x-script.perl-module"),
                new KeyValuePair<string, string>("pm4",	"application/x-pagemaker"),
                new KeyValuePair<string, string>("pm5",	"application/x-pagemaker"),
                new KeyValuePair<string, string>("png",	"image/png"),
                new KeyValuePair<string, string>("pnm",	"application/x-portable-anymap"),
                new KeyValuePair<string, string>("pnm",	"image/x-portable-anymap"),
                new KeyValuePair<string, string>("pot",	"application/mspowerpoint"),
                new KeyValuePair<string, string>("pot",	"application/vnd.ms-powerpoint"),
                new KeyValuePair<string, string>("pov",	"model/x-pov"),
                new KeyValuePair<string, string>("ppa",	"application/vnd.ms-powerpoint"),
                new KeyValuePair<string, string>("ppm",	"image/x-portable-pixmap"),
                new KeyValuePair<string, string>("pps",	"application/mspowerpoint"),
                new KeyValuePair<string, string>("pps",	"application/vnd.ms-powerpoint"),
                new KeyValuePair<string, string>("ppt",	"application/mspowerpoint"),
                new KeyValuePair<string, string>("ppt",	"application/powerpoint"),
                new KeyValuePair<string, string>("ppt",	"application/vnd.ms-powerpoint"),
                new KeyValuePair<string, string>("ppt",	"application/x-mspowerpoint"),
                new KeyValuePair<string, string>("ppz",	"application/mspowerpoint"),
                new KeyValuePair<string, string>("pre",	"application/x-freelance"),
                new KeyValuePair<string, string>("prt",	"application/pro_eng"),
                new KeyValuePair<string, string>("ps",	"application/postscript"),
                new KeyValuePair<string, string>("psd",	"application/octet-stream"),
                new KeyValuePair<string, string>("pvu",	"paleovu/x-pv"),
                new KeyValuePair<string, string>("pwz",	"application/vnd.ms-powerpoint"),
                new KeyValuePair<string, string>("py",	"text/x-script.phyton"),
                new KeyValuePair<string, string>("pyc",	"applicaiton/x-bytecode.python"),
                new KeyValuePair<string, string>("qcp",	"audio/vnd.qcelp"),
                new KeyValuePair<string, string>("qd3",	"x-world/x-3dmf"),
                new KeyValuePair<string, string>("qd3d",	"x-world/x-3dmf"),
                new KeyValuePair<string, string>("qif",	"image/x-quicktime"),
                new KeyValuePair<string, string>("qt",	"video/quicktime"),
                new KeyValuePair<string, string>("qtc",	"video/x-qtc"),
                new KeyValuePair<string, string>("qti",	"image/x-quicktime"),
                new KeyValuePair<string, string>("qtif",	"image/x-quicktime"),
                new KeyValuePair<string, string>("ra",	"audio/x-pn-realaudio"),
                new KeyValuePair<string, string>("ra",	"audio/x-pn-realaudio-plugin"),
                new KeyValuePair<string, string>("ra",	"audio/x-realaudio"),
                new KeyValuePair<string, string>("ram",	"audio/x-pn-realaudio"),
                new KeyValuePair<string, string>("ras",	"application/x-cmu-raster"),
                new KeyValuePair<string, string>("ras",	"image/cmu-raster"),
                new KeyValuePair<string, string>("ras",	"image/x-cmu-raster"),
                new KeyValuePair<string, string>("rast",	"image/cmu-raster"),
                new KeyValuePair<string, string>("rexx",	"text/x-script.rexx"),
                new KeyValuePair<string, string>("rf",	"image/vnd.rn-realflash"),
                new KeyValuePair<string, string>("rgb",	"image/x-rgb"),
                new KeyValuePair<string, string>("rm",	"application/vnd.rn-realmedia"),
                new KeyValuePair<string, string>("rm",	"audio/x-pn-realaudio"),
                new KeyValuePair<string, string>("rmi",	"audio/mid"),
                new KeyValuePair<string, string>("rmm",	"audio/x-pn-realaudio"),
                new KeyValuePair<string, string>("rmp",	"audio/x-pn-realaudio"),
                new KeyValuePair<string, string>("rmp",	"audio/x-pn-realaudio-plugin"),
                new KeyValuePair<string, string>("rng",	"application/ringing-tones"),
                new KeyValuePair<string, string>("rng",	"application/vnd.nokia.ringing-tone"),
                new KeyValuePair<string, string>("rnx",	"application/vnd.rn-realplayer"),
                new KeyValuePair<string, string>("roff",	"application/x-troff"),
                new KeyValuePair<string, string>("rp",	"image/vnd.rn-realpix"),
                new KeyValuePair<string, string>("rpm",	"audio/x-pn-realaudio-plugin"),
                new KeyValuePair<string, string>("rt",	"text/richtext"),
                new KeyValuePair<string, string>("rt",	"text/vnd.rn-realtext"),
                new KeyValuePair<string, string>("rtf",	"application/rtf"),
                new KeyValuePair<string, string>("rtf",	"application/x-rtf"),
                new KeyValuePair<string, string>("rtf",	"text/richtext"),
                new KeyValuePair<string, string>("rtx",	"application/rtf"),
                new KeyValuePair<string, string>("rtx",	"text/richtext"),
                new KeyValuePair<string, string>("rv",	"video/vnd.rn-realvideo"),
                new KeyValuePair<string, string>("s",	"text/x-asm"),
                new KeyValuePair<string, string>("s3m",	"audio/s3m"),
                new KeyValuePair<string, string>("saveme",	"application/octet-stream"),
                new KeyValuePair<string, string>("sbk",	"application/x-tbook"),
                new KeyValuePair<string, string>("scm",	"application/x-lotusscreencam"),
                new KeyValuePair<string, string>("scm",	"text/x-script.guile"),
                new KeyValuePair<string, string>("scm",	"text/x-script.scheme"),
                new KeyValuePair<string, string>("scm",	"video/x-scm"),
                new KeyValuePair<string, string>("sdml",	"text/plain"),
                new KeyValuePair<string, string>("sdp",	"application/sdp"),
                new KeyValuePair<string, string>("sdp",	"application/x-sdp"),
                new KeyValuePair<string, string>("sdr",	"application/sounder"),
                new KeyValuePair<string, string>("sea",	"application/sea"),
                new KeyValuePair<string, string>("sea",	"application/x-sea"),
                new KeyValuePair<string, string>("set",	"application/set"),
                new KeyValuePair<string, string>("sgm",	"text/sgml"),
                new KeyValuePair<string, string>("sgm",	"text/x-sgml"),
                new KeyValuePair<string, string>("sgml",	"text/sgml"),
                new KeyValuePair<string, string>("sgml",	"text/x-sgml"),
                new KeyValuePair<string, string>("sh",	"application/x-bsh"),
                new KeyValuePair<string, string>("sh",	"application/x-sh"),
                new KeyValuePair<string, string>("sh",	"application/x-shar"),
                new KeyValuePair<string, string>("sh",	"text/x-script.sh"),
                new KeyValuePair<string, string>("shar",	"application/x-bsh"),
                new KeyValuePair<string, string>("shar",	"application/x-shar"),
                new KeyValuePair<string, string>("shtml",	"text/html"),
                new KeyValuePair<string, string>("shtml",	"text/x-server-parsed-html"),
                new KeyValuePair<string, string>("sid",	"audio/x-psid"),
                new KeyValuePair<string, string>("sit",	"application/x-sit"),
                new KeyValuePair<string, string>("sit",	"application/x-stuffit"),
                new KeyValuePair<string, string>("skd",	"application/x-koan"),
                new KeyValuePair<string, string>("skm",	"application/x-koan"),
                new KeyValuePair<string, string>("skp",	"application/x-koan"),
                new KeyValuePair<string, string>("skt",	"application/x-koan"),
                new KeyValuePair<string, string>("sl",	"application/x-seelogo"),
                new KeyValuePair<string, string>("smi",	"application/smil"),
                new KeyValuePair<string, string>("smil",	"application/smil"),
                new KeyValuePair<string, string>("snd",	"audio/basic"),
                new KeyValuePair<string, string>("snd",	"audio/x-adpcm"),
                new KeyValuePair<string, string>("sol",	"application/solids"),
                new KeyValuePair<string, string>("spc",	"application/x-pkcs7-certificates"),
                new KeyValuePair<string, string>("spc",	"text/x-speech"),
                new KeyValuePair<string, string>("spl",	"application/futuresplash"),
                new KeyValuePair<string, string>("spr",	"application/x-sprite"),
                new KeyValuePair<string, string>("sprite",	"application/x-sprite"),
                new KeyValuePair<string, string>("src",	"application/x-wais-source"),
                new KeyValuePair<string, string>("ssi",	"text/x-server-parsed-html"),
                new KeyValuePair<string, string>("ssm",	"application/streamingmedia"),
                new KeyValuePair<string, string>("sst",	"application/vnd.ms-pki.certstore"),
                new KeyValuePair<string, string>("step",	"application/step"),
                new KeyValuePair<string, string>("stl",	"application/sla"),
                new KeyValuePair<string, string>("stl",	"application/vnd.ms-pki.stl"),
                new KeyValuePair<string, string>("stl",	"application/x-navistyle"),
                new KeyValuePair<string, string>("stp",	"application/step"),
                new KeyValuePair<string, string>("sv4cpio",	"application/x-sv4cpio"),
                new KeyValuePair<string, string>("sv4crc",	"application/x-sv4crc"),
                new KeyValuePair<string, string>("svf",	"image/vnd.dwg"),
                new KeyValuePair<string, string>("svf",	"image/x-dwg"),
                new KeyValuePair<string, string>("svr",	"application/x-world"),
                new KeyValuePair<string, string>("svr",	"x-world/x-svr"),
                new KeyValuePair<string, string>("swf",	"application/x-shockwave-flash"),
                new KeyValuePair<string, string>("t",	"application/x-troff"),
                new KeyValuePair<string, string>("talk",	"text/x-speech"),
                new KeyValuePair<string, string>("tar",	"application/x-tar"),
                new KeyValuePair<string, string>("tbk",	"application/toolbook"),
                new KeyValuePair<string, string>("tbk",	"application/x-tbook"),
                new KeyValuePair<string, string>("tcl",	"application/x-tcl"),
                new KeyValuePair<string, string>("tcl",	"text/x-script.tcl"),
                new KeyValuePair<string, string>("tcsh",	"text/x-script.tcsh"),
                new KeyValuePair<string, string>("tex",	"application/x-tex"),
                new KeyValuePair<string, string>("texi",	"application/x-texinfo"),
                new KeyValuePair<string, string>("texinfo",	"application/x-texinfo"),
                new KeyValuePair<string, string>("text",	"application/plain"),
                new KeyValuePair<string, string>("text",	"text/plain"),
                new KeyValuePair<string, string>("tgz",	"application/gnutar"),
                new KeyValuePair<string, string>("tgz",	"application/x-compressed"),
                new KeyValuePair<string, string>("tif",	"image/tiff"),
                new KeyValuePair<string, string>("tif",	"image/x-tiff"),
                new KeyValuePair<string, string>("tiff",	"image/tiff"),
                new KeyValuePair<string, string>("tiff",	"image/x-tiff"),
                new KeyValuePair<string, string>("tr",	"application/x-troff"),
                new KeyValuePair<string, string>("tsi",	"audio/tsp-audio"),
                new KeyValuePair<string, string>("tsp",	"application/dsptype"),
                new KeyValuePair<string, string>("tsp",	"audio/tsplayer"),
                new KeyValuePair<string, string>("tsv",	"text/tab-separated-values"),
                new KeyValuePair<string, string>("turbot",	"image/florian"),
                new KeyValuePair<string, string>("txt",	"text/plain"),
                new KeyValuePair<string, string>("uil",	"text/x-uil"),
                new KeyValuePair<string, string>("uni",	"text/uri-list"),
                new KeyValuePair<string, string>("unis",	"text/uri-list"),
                new KeyValuePair<string, string>("unv",	"application/i-deas"),
                new KeyValuePair<string, string>("uri",	"text/uri-list"),
                new KeyValuePair<string, string>("uris",	"text/uri-list"),
                new KeyValuePair<string, string>("ustar",	"application/x-ustar"),
                new KeyValuePair<string, string>("ustar",	"multipart/x-ustar"),
                new KeyValuePair<string, string>("uu",	"application/octet-stream"),
                new KeyValuePair<string, string>("uu",	"text/x-uuencode"),
                new KeyValuePair<string, string>("uue",	"text/x-uuencode"),
                new KeyValuePair<string, string>("vcd",	"application/x-cdlink"),
                new KeyValuePair<string, string>("vcs",	"text/x-vcalendar"),
                new KeyValuePair<string, string>("vda",	"application/vda"),
                new KeyValuePair<string, string>("vdo",	"video/vdo"),
                new KeyValuePair<string, string>("vew",	"application/groupwise"),
                new KeyValuePair<string, string>("viv",	"video/vivo"),
                new KeyValuePair<string, string>("viv",	"video/vnd.vivo"),
                new KeyValuePair<string, string>("vivo",	"video/vivo"),
                new KeyValuePair<string, string>("vivo",	"video/vnd.vivo"),
                new KeyValuePair<string, string>("vmd",	"application/vocaltec-media-desc"),
                new KeyValuePair<string, string>("vmf",	"application/vocaltec-media-file"),
                new KeyValuePair<string, string>("voc",	"audio/voc"),
                new KeyValuePair<string, string>("voc",	"audio/x-voc"),
                new KeyValuePair<string, string>("vos",	"video/vosaic"),
                new KeyValuePair<string, string>("vox",	"audio/voxware"),
                new KeyValuePair<string, string>("vqe",	"audio/x-twinvq-plugin"),
                new KeyValuePair<string, string>("vqf",	"audio/x-twinvq"),
                new KeyValuePair<string, string>("vql",	"audio/x-twinvq-plugin"),
                new KeyValuePair<string, string>("vrml",	"application/x-vrml"),
                new KeyValuePair<string, string>("vrml",	"model/vrml"),
                new KeyValuePair<string, string>("vrml",	"x-world/x-vrml"),
                new KeyValuePair<string, string>("vrt",	"x-world/x-vrt"),
                new KeyValuePair<string, string>("vsd",	"application/x-visio"),
                new KeyValuePair<string, string>("vst",	"application/x-visio"),
                new KeyValuePair<string, string>("vsw",	"application/x-visio"),
                new KeyValuePair<string, string>("w60",	"application/wordperfect6.0"),
                new KeyValuePair<string, string>("w61",	"application/wordperfect6.1"),
                new KeyValuePair<string, string>("w6w",	"application/msword"),
                new KeyValuePair<string, string>("wav",	"audio/wav"),
                new KeyValuePair<string, string>("wav",	"audio/x-wav"),
                new KeyValuePair<string, string>("wb1",	"application/x-qpro"),
                new KeyValuePair<string, string>("wbmp",	"image/vnd.wap.wbmp"),
                new KeyValuePair<string, string>("web",	"application/vnd.xara"),
                new KeyValuePair<string, string>("wiz",	"application/msword"),
                new KeyValuePair<string, string>("wk1",	"application/x-123"),
                new KeyValuePair<string, string>("wmf",	"windows/metafile"),
                new KeyValuePair<string, string>("wml",	"text/vnd.wap.wml"),
                new KeyValuePair<string, string>("wmlc",	"application/vnd.wap.wmlc"),
                new KeyValuePair<string, string>("wmls",	"text/vnd.wap.wmlscript"),
                new KeyValuePair<string, string>("wmlsc",	"application/vnd.wap.wmlscriptc"),
                new KeyValuePair<string, string>("word",	"application/msword"),
                new KeyValuePair<string, string>("wp",	"application/wordperfect"),
                new KeyValuePair<string, string>("wp5",	"application/wordperfect"),
                new KeyValuePair<string, string>("wp5",	"application/wordperfect6.0"),
                new KeyValuePair<string, string>("wp6",	"application/wordperfect"),
                new KeyValuePair<string, string>("wpd",	"application/wordperfect"),
                new KeyValuePair<string, string>("wpd",	"application/x-wpwin"),
                new KeyValuePair<string, string>("wq1",	"application/x-lotus"),
                new KeyValuePair<string, string>("wri",	"application/mswrite"),
                new KeyValuePair<string, string>("wri",	"application/x-wri"),
                new KeyValuePair<string, string>("wrl",	"application/x-world"),
                new KeyValuePair<string, string>("wrl",	"model/vrml"),
                new KeyValuePair<string, string>("wrl",	"x-world/x-vrml"),
                new KeyValuePair<string, string>("wrz",	"model/vrml"),
                new KeyValuePair<string, string>("wrz",	"x-world/x-vrml"),
                new KeyValuePair<string, string>("wsc",	"text/scriplet"),
                new KeyValuePair<string, string>("wsrc",	"application/x-wais-source"),
                new KeyValuePair<string, string>("wtk",	"application/x-wintalk"),
                new KeyValuePair<string, string>("xbm",	"image/x-xbitmap"),
                new KeyValuePair<string, string>("xbm",	"image/x-xbm"),
                new KeyValuePair<string, string>("xbm",	"image/xbm"),
                new KeyValuePair<string, string>("xdr",	"video/x-amt-demorun"),
                new KeyValuePair<string, string>("xgz",	"xgl/drawing"),
                new KeyValuePair<string, string>("xif",	"image/vnd.xiff"),
                new KeyValuePair<string, string>("xl",	"application/excel"),
                new KeyValuePair<string, string>("xla",	"application/excel"),
                new KeyValuePair<string, string>("xla",	"application/x-excel"),
                new KeyValuePair<string, string>("xla",	"application/x-msexcel"),
                new KeyValuePair<string, string>("xlb",	"application/excel"),
                new KeyValuePair<string, string>("xlb",	"application/vnd.ms-excel"),
                new KeyValuePair<string, string>("xlb",	"application/x-excel"),
                new KeyValuePair<string, string>("xlc",	"application/excel"),
                new KeyValuePair<string, string>("xlc",	"application/vnd.ms-excel"),
                new KeyValuePair<string, string>("xlc",	"application/x-excel"),
                new KeyValuePair<string, string>("xld",	"application/excel"),
                new KeyValuePair<string, string>("xld",	"application/x-excel"),
                new KeyValuePair<string, string>("xlk",	"application/excel"),
                new KeyValuePair<string, string>("xlk",	"application/x-excel"),
                new KeyValuePair<string, string>("xll",	"application/excel"),
                new KeyValuePair<string, string>("xll",	"application/vnd.ms-excel"),
                new KeyValuePair<string, string>("xll",	"application/x-excel"),
                new KeyValuePair<string, string>("xlm",	"application/excel"),
                new KeyValuePair<string, string>("xlm",	"application/vnd.ms-excel"),
                new KeyValuePair<string, string>("xlm",	"application/x-excel"),
                new KeyValuePair<string, string>("xls",	"application/excel"),
                new KeyValuePair<string, string>("xls",	"application/vnd.ms-excel"),
                new KeyValuePair<string, string>("xls",	"application/x-excel"),
                new KeyValuePair<string, string>("xls",	"application/x-msexcel"),
                new KeyValuePair<string, string>("xlt",	"application/excel"),
                new KeyValuePair<string, string>("xlt",	"application/x-excel"),
                new KeyValuePair<string, string>("xlv",	"application/excel"),
                new KeyValuePair<string, string>("xlv",	"application/x-excel"),
                new KeyValuePair<string, string>("xlw",	"application/excel"),
                new KeyValuePair<string, string>("xlw",	"application/vnd.ms-excel"),
                new KeyValuePair<string, string>("xlw",	"application/x-excel"),
                new KeyValuePair<string, string>("xlw",	"application/x-msexcel"),
                new KeyValuePair<string, string>("xm",	"audio/xm"),
                new KeyValuePair<string, string>("xml",	"application/xml"),
                new KeyValuePair<string, string>("xml",	"text/xml"),
                new KeyValuePair<string, string>("xmz",	"xgl/movie"),
                new KeyValuePair<string, string>("xpix",	"application/x-vnd.ls-xpix"),
                new KeyValuePair<string, string>("xpm",	"image/x-xpixmap"),
                new KeyValuePair<string, string>("xpm",	"image/xpm"),
                new KeyValuePair<string, string>("x-png",	"image/png"),
                new KeyValuePair<string, string>("xsr",	"video/x-amt-showrun"),
                new KeyValuePair<string, string>("xwd",	"image/x-xwd"),
                new KeyValuePair<string, string>("xwd",	"image/x-xwindowdump"),
                new KeyValuePair<string, string>("xyz",	"chemical/x-pdb"),
                new KeyValuePair<string, string>("z",	"application/x-compress"),
                new KeyValuePair<string, string>("z",	"application/x-compressed"),
                new KeyValuePair<string, string>("zip",	"application/x-compressed"),
                new KeyValuePair<string, string>("zip",	"application/x-zip-compressed"),
                new KeyValuePair<string, string>("zip",	"application/zip"),
                new KeyValuePair<string, string>("zip",	"multipart/x-zip"),
                new KeyValuePair<string, string>("zoo",	"application/octet-stream"),
                new KeyValuePair<string, string>("zsh",	"text/x-script.zsh")
            //{"ai", "application/postscript"},
            //{"aif", "audio/x-aiff"},
            //{"aifc", "audio/x-aiff"},
            //{"aiff", "audio/x-aiff"},
            //{"asc", "text/plain"},
            //{"atom", "application/atom+xml"},
            //{"au", "audio/basic"},
            //{"avi", "video/x-msvideo"},
            //{"bcpio", "application/x-bcpio"},
            //{"bin", "application/octet-stream"},
            //{"bmp", "image/bmp"},
            //{"cdf", "application/x-netcdf"},
            //{"cgm", "image/cgm"},
            //{"class", "application/octet-stream"},
            //{"cpio", "application/x-cpio"},
            //{"cpt", "application/mac-compactpro"},
            //{"csh", "application/x-csh"},
            //{"css", "text/css"},
            //{"dcr", "application/x-director"},
            //{"dif", "video/x-dv"},
            //{"dir", "application/x-director"},
            //{"djv", "image/vnd.djvu"},
            //{"djvu", "image/vnd.djvu"},
            //{"dll", "application/octet-stream"},
            //{"dmg", "application/octet-stream"},
            //{"dms", "application/octet-stream"},
            //{"doc", "application/msword"},
            //{"docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
            //{"dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
            //{"docm","application/vnd.ms-word.document.macroEnabled.12"},
            //{"dotm","application/vnd.ms-word.template.macroEnabled.12"},
            //{"dtd", "application/xml-dtd"},
            //{"dv", "video/x-dv"},
            //{"dvi", "application/x-dvi"},
            //{"dxr", "application/x-director"},
            //{"eps", "application/postscript"},
            //{"etx", "text/x-setext"},
            //{"exe", "application/octet-stream"},
            //{"ez", "application/andrew-inset"},
            //{"gif", "image/gif"},
            //{"gram", "application/srgs"},
            //{"grxml", "application/srgs+xml"},
            //{"gtar", "application/x-gtar"},
            //{"hdf", "application/x-hdf"},
            //{"hqx", "application/mac-binhex40"},
            //{"htm", "text/html"},
            //{"html", "text/html"},
            //{"ice", "x-conference/x-cooltalk"},
            //{"ico", "image/x-icon"},
            //{"ics", "text/calendar"},
            //{"ief", "image/ief"},
            //{"ifb", "text/calendar"},
            //{"iges", "model/iges"},
            //{"igs", "model/iges"},
            //{"jnlp", "application/x-java-jnlp-file"},
            //{"jp2", "image/jp2"},
            //{"jpe", "image/jpeg"},
            //{"jpeg", "image/jpeg"},
            //{"jpg", "image/jpeg"},
            //{"js", "application/x-javascript"},
            //{"kar", "audio/midi"},
            //{"latex", "application/x-latex"},
            //{"lha", "application/octet-stream"},
            //{"lzh", "application/octet-stream"},
            //{"m3u", "audio/x-mpegurl"},
            //{"m4a", "audio/mp4a-latm"},
            //{"m4b", "audio/mp4a-latm"},
            //{"m4p", "audio/mp4a-latm"},
            //{"m4u", "video/vnd.mpegurl"},
            //{"m4v", "video/x-m4v"},
            //{"mac", "image/x-macpaint"},
            //{"man", "application/x-troff-man"},
            //{"mathml", "application/mathml+xml"},
            //{"me", "application/x-troff-me"},
            //{"mesh", "model/mesh"},
            //{"mid", "audio/midi"},
            //{"midi", "audio/midi"},
            //{"mif", "application/vnd.mif"},
            //{"mov", "video/quicktime"},
            //{"movie", "video/x-sgi-movie"},
            //{"mp2", "audio/mpeg"},
            //{"mp3", "audio/mpeg"},
            //{"mp4", "video/mp4"},
            //{"mpe", "video/mpeg"},
            //{"mpeg", "video/mpeg"},
            //{"mpg", "video/mpeg"},
            //{"mpga", "audio/mpeg"},
            //{"ms", "application/x-troff-ms"},
            //{"msh", "model/mesh"},
            //{"mxu", "video/vnd.mpegurl"},
            //{"nc", "application/x-netcdf"},
            //{"oda", "application/oda"},
            //{"ogg", "application/ogg"},
            //{"pbm", "image/x-portable-bitmap"},
            //{"pct", "image/pict"},
            //{"pdb", "chemical/x-pdb"},
            //{"pdf", "application/pdf"},
            //{"pgm", "image/x-portable-graymap"},
            //{"pgn", "application/x-chess-pgn"},
            //{"pic", "image/pict"},
            //{"pict", "image/pict"},
            //{"png", "image/png"}, 
            //{"pnm", "image/x-portable-anymap"},
            //{"pnt", "image/x-macpaint"},
            //{"pntg", "image/x-macpaint"},
            //{"ppm", "image/x-portable-pixmap"},
            //{"ppt", "application/vnd.ms-powerpoint"},
            //{"pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation"},
            //{"potx","application/vnd.openxmlformats-officedocument.presentationml.template"},
            //{"ppsx","application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
            //{"ppam","application/vnd.ms-powerpoint.addin.macroEnabled.12"},
            //{"pptm","application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
            //{"potm","application/vnd.ms-powerpoint.template.macroEnabled.12"},
            //{"ppsm","application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
            //{"ps", "application/postscript"},
            //{"qt", "video/quicktime"},
            //{"qti", "image/x-quicktime"},
            //{"qtif", "image/x-quicktime"},
            //{"ra", "audio/x-pn-realaudio"},
            //{"ram", "audio/x-pn-realaudio"},
            //{"ras", "image/x-cmu-raster"},
            //{"rdf", "application/rdf+xml"},
            //{"rgb", "image/x-rgb"},
            //{"rm", "application/vnd.rn-realmedia"},
            //{"roff", "application/x-troff"},
            //{"rtf", "text/rtf"},
            //{"rtx", "text/richtext"},
            //{"sgm", "text/sgml"},
            //{"sgml", "text/sgml"},
            //{"sh", "application/x-sh"},
            //{"shar", "application/x-shar"},
            //{"silo", "model/mesh"},
            //{"sit", "application/x-stuffit"},
            //{"skd", "application/x-koan"},
            //{"skm", "application/x-koan"},
            //{"skp", "application/x-koan"},
            //{"skt", "application/x-koan"},
            //{"smi", "application/smil"},
            //{"smil", "application/smil"},
            //{"snd", "audio/basic"},
            //{"so", "application/octet-stream"},
            //{"spl", "application/x-futuresplash"},
            //{"src", "application/x-wais-source"},
            //{"sv4cpio", "application/x-sv4cpio"},
            //{"sv4crc", "application/x-sv4crc"},
            //{"svg", "image/svg+xml"},
            //{"swf", "application/x-shockwave-flash"},
            //{"t", "application/x-troff"},
            //{"tar", "application/x-tar"},
            //{"tcl", "application/x-tcl"},
            //{"tex", "application/x-tex"},
            //{"texi", "application/x-texinfo"},
            //{"texinfo", "application/x-texinfo"},
            //{"tif", "image/tiff"},
            //{"tiff", "image/tiff"},
            //{"tr", "application/x-troff"},
            //{"tsv", "text/tab-separated-values"},
            //{"txt", "text/plain"},
            //{"ustar", "application/x-ustar"},
            //{"vcd", "application/x-cdlink"},
            //{"vrml", "model/vrml"},
            //{"vxml", "application/voicexml+xml"},
            //{"wav", "audio/x-wav"},
            //{"wbmp", "image/vnd.wap.wbmp"},
            //{"wbmxl", "application/vnd.wap.wbxml"},
            //{"wml", "text/vnd.wap.wml"},
            //{"wmlc", "application/vnd.wap.wmlc"},
            //{"wmls", "text/vnd.wap.wmlscript"},
            //{"wmlsc", "application/vnd.wap.wmlscriptc"},
            //{"wrl", "model/vrml"},
            //{"xbm", "image/x-xbitmap"},
            //{"xht", "application/xhtml+xml"},
            //{"xhtml", "application/xhtml+xml"},
            //{"xls", "application/vnd.ms-excel"},                        
            //{"xml", "application/xml"},
            //{"xpm", "image/x-xpixmap"},
            //{"xsl", "application/xml"},
            //{"xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
            //{"xltx","application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
            //{"xlsm","application/vnd.ms-excel.sheet.macroEnabled.12"},
            //{"xltm","application/vnd.ms-excel.template.macroEnabled.12"},
            //{"xlam","application/vnd.ms-excel.addin.macroEnabled.12"},
            //{"xlsb","application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
            //{"xslt", "application/xslt+xml"},
            //{"xul", "application/vnd.mozilla.xul+xml"},
            //{"xwd", "image/x-xwindowdump"},
            //{"xyz", "chemical/x-xyz"},
            //{"zip", "application/zip"}
            };

        public static string GetMIMEType(string fileName) {
            string extension = Path.GetExtension(fileName).ToLowerInvariant();

            if (extension.Length > 0) {
                extension = extension.Remove(0, 1);

                var items = MIMETypesDictionary.Where(w => w.Key == extension);
                if (items.Count() > 0)
                    return items.FirstOrDefault().Value;
            }

            return "unknown/unknown";
        }

        public static string GetExtensionFromMIMEType(string mime) {
            var list = MIMETypesDictionary.Where(w => w.Value == mime);
            if (list.Count() > 0) {
                return list.FirstOrDefault().Key;
            }

            return "";
        }

    }
}
